In [ ]:
print("Hello World")

# Cara assign variabel di Phyton
a = 1
a = "Jevon"
a = 0.5
print(type(a))

name = input("Input name: ")
print("Inputted name:", name)
print(f"Inputted name: {name}")
print("Inputted name: " + name)

Hello World
<class 'float'>
Input name: Jevon
Inputted name: Jevon
Inputted name: Jevon
Inputted name: Jevon

In [ ]:
# Arithmetic + - * / % ** //
# + tambah
# - kurang
# * kali
# / bagi
# % modulo
# ** eksponen
# // floor division

b = 5
print(b/2)
print(b//2)
print(b%2)
print(b**3)

# Assignment Operator
print("----------------------------")
c = 1
c += 5
c *= 2
c **= 3
print(c)

2.5
2
1
125
----------------------------
1728

In [ ]:
# Comparison Operator
# == equals
# != not equal
# > greater than
# < less than
# >= greater than or equal
# <= less than or equal

print(10 == 12)
print(10 != 12)
print(10 < 12)
print(10 > 12)

False
True
True
False

In [ ]:
# Logical Operator
# and
# or
# not

print((10 == 10) or (10 != 10))
print(not(10 == 10))
print("---------------------------")

# Identity Operator
# is -> return true kalau kedua objek sama
# is not

list_1 = [1, 23, 5]
list_2 = [1, 23, 5]
list_3 = list_1
print(list_1 == list_2)
print(list_1 is list_2)
print(list_3 is list_1)

True
False
---------------------------
True
False
True

In [ ]:
# Selection

num = 5
if(num > 5):
  print("Num is > 5")
elif(num < 5):
  print("Num is < 5")
else:
  print("Num is 5")

Num is 5

In [ ]:
# Repetition

temp = 0
while(temp < 10):
  print(temp, end = " ")
  temp += 1

print("")

list_temp = [32, 13, 52, 62, 11]
for i in list_temp:
  print(i)

for i in range(4):
  print(i)

for i in range(5, 11):
  print(i)

print(100 in list_temp)

0 1 2 3 4 5 6 7 8 9
32
13
52
62
11
0
1
2
3
5
6
7
8
9
10
False

In [ ]:
# Function

def plus_ten(num):
  return num+10

def plus_10(num):
  print(num+10)

print(plus_ten(11))
plus_10(11)

21
21

In [ ]:
# Built-In Data Structure

# List -> seperti array, tapi bisa menampung banyak tipe data, mutable (bisa ditambahin, remove, update), direpresentasikan dengan []
list_satu = [10, 23, 54, 5, 14]
print(list_satu)
list_satu[1] = "Jevon"
print(list_satu)

# Set -> unordered, nilai yang disimpan unik (tidak duplikat), tidak bisa nembak index, direpresentasikan dengan {}
set_satu = {10, 34, "Meja", 11, 11}
print(set_satu)

# Tuple -> tidak bisa diubah atau ditambah-tambah, sudah fix nilainya, direpresentasikan dengan ()
tuple_satu = (10, 32, 64, 21)
print(tuple_satu)

# Dictionary -> menyimpan key-value pair
dict_capitals = {"Indonesia":"Jakarta", "Jepang":"Tokyo"}
dict_capitals["Thailand"] = "Bangkok"
print(dict_capitals["Jepang"])
print(dict_capitals)

[10, 23, 54, 5, 14]
[10, 'Jevon', 54, 5, 14]
{'Meja', 10, 11, 34}
(10, 32, 64, 21)
Tokyo
{'Indonesia': 'Jakarta', 'Jepang': 'Tokyo', 'Thailand': 'Bangkok'}

In [ ]:
# Slicing Data

list_1 = [10, 11, 23, 34, 14]

# start : end : jump/gap
print(list_1[0:4:2])

[10, 23]